# Site settings
title: '@sbastidasr'
header-img: img/home-bg.png
email: sbastidasr@gmail.com
description: "My blog. About development & stuff"
baseurl: ""
url: "http://sbastidasr.com"
twitter_username: sbastidasr
github_username:  sbastidasr
facebook_username:  sbastidasr

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
